# Generated by Django 3.2.25 on 2024-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ronda',
            field=models.IntegerField(default=1),
        ),
    ]
